### ISSUE TITLE
pad.partidopirata.com.ar

### ISSUE THREAD

**Issue by fauno** [piratas-ar/elaine#1]
- [x] Instalar y actualizar pad.partidopirata.com.ar
- [x] Importar el backup de la base de datos de threepwood

**Comment by sudoaza** [comment]
dale esta es mia

2014-11-12 20:35 GMT-03:00 fauno notifications@github.com:

**Comment by fauno** [comment]
aza notifications@github.com writes:

> dale esta es mia

ponelo en el makefile asi ya nos queda

## 

P)

**Comment by fauno** [comment]
los archivos están en /home/fauno/threepwood hay un etherpad.deb?

**Comment by fauno** [comment]
lo hice andar con nginx-passenger \o/
